Traceback (most recent call last):
  File "/home/bondar1983ovdoc1/newswebsite/env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
  File "/home/bondar1983ovdoc1/newswebsite/env/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 920, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: attempt to write a readonly database

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bondar1983ovdoc1/newswebsite/appnews.py", line 100, in <module>
    getnews_snippets()
  File "/home/bondar1983ovdoc1/newswebsite/appnews.py", line 25, in getnews_snippets
    getnews.get_news_snippets()
  File "/home/bondar1983ovdoc1/newswebsite/webapp/news/parsers/getnews.py", line 109, in get_news_snippets
    save_news(title, url, published)
  File "/home/bondar1983ovdoc1/newswebsite/webapp/news/parsers/utils.py", line 26, in save_news
    db.session.commit()						# save in DB		
  File "/home/bondar1983ovdoc1/newswebsite/env/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 553, in commit
    return self._proxied.commit()
  File "/home/bondar1983ovdoc1/newswebsite/env/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1906, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/bondar1983ovdoc1/newswebsite/env/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/bondar1983ovdoc1/newswebsite/env/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1221, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/bondar1983ovdoc1/newswebsite/env/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/bondar1983ovdoc1/newswebsite/env/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1196, in _prepare_impl
    self.session.flush()
  File "/home/bondar1983ovdoc1/newswebsite/env/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4154, in flush
    self._flush(objects)
  File "/home/bondar1983ovdoc1/newswebsite/env/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4290, in _flush
    with util.safe_reraise():
  File "/home/bondar1983ovdoc1/newswebsite/env/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/bondar1983ovdoc1/newswebsite/env/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4251, in _flush
    flush_context.execute()
  File "/home/bondar1983ovdoc1/newswebsite/env/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 467, in execute
    rec.execute(self)
  File "/home/bondar1983ovdoc1/newswebsite/env/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 644, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/bondar1983ovdoc1/newswebsite/env/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/bondar1983ovdoc1/newswebsite/env/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1223, in _emit_insert_statements
    result = connection.execute(
  File "/home/bondar1983ovdoc1/newswebsite/env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1413, in execute
    return meth(
  File "/home/bondar1983ovdoc1/newswebsite/env/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/bondar1983ovdoc1/newswebsite/env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/bondar1983ovdoc1/newswebsite/env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1841, in _execute_context
    return self._exec_single_context(
  File "/home/bondar1983ovdoc1/newswebsite/env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1982, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/bondar1983ovdoc1/newswebsite/env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/bondar1983ovdoc1/newswebsite/env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
  File "/home/bondar1983ovdoc1/newswebsite/env/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 920, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) attempt to write a readonly database
[SQL: INSERT INTO news (title, url, published, text) VALUES (?, ?, ?, ?)]
[parameters: ('UK announces over £100M to support ‘agile’ AI regulation', 'https://www.artificialintelligence-news.com/2024/02/06/uk-announces-over-100m-support-agile-ai-regulation/', '2024-02-06 00:00:00.000000', None)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
